image: ubuntu

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
# variables:
#   DOCKER_DRIVER: overlay2

services:
  - docker

stages:
  - build
  - test
  - doc
  - pages

before_script:
    - apt-get update 
    - apt-get install -y python3-pip python3-dev build-essential
    - pip3 install -r requirements.txt
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE/test_doc:task_4

# build:
#     stage: build
#     script:
#         - docker build -t $CONTAINER_IMAGE .
#         - docker push $CI_REGISTRY_IMAGE/test_doc:task_4

# test:
#     stage: test
#     script:
#         - docker pull $CONTAINER_IMAGE
#         - docker run $CONTAINER_IMAGE

doc:
    stage: doc
    script:
        - sphinx-apidoc -f -o doc .

pages:
    stage: pages
    script:
        # - docker pull $CONTAINER_IMAGE
        # - docker run -w /project/doc $CONTAINER_IMAGE make html
        # - docker cp $CONTAINER_IMAGE:/project/doc/_build/html/ ./public
        - cd doc
        - make html
        - cp _build/html/ ../public
    artifacts:
        paths:
            - public
    # only:
    #     - master
    #     - release
