image: ubuntu

before_script:
    - apt-get -qy update
    - apt-get install -y make build-essential python3 python3-dev python3-setuptools python3-sphinx python3-pip
    # - apk --no-cache add python3 python3-dev py-pip
    # - apk --no-cache add make

pages:
    script:
        - pip3 install --upgrade pip
        - pip3 install sphinx numpy sklearn
        - cd doc
        - make html
        - mv _build/html ../public
        - cd ..
    artifacts:
        paths:
            - public
    only:
        - master
