image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - cd doc
  - make html
  - cd ..
  artifacts:
    paths:
    - doc/_build/html
  only:
  - master
