image: ubuntu

before_script:
    - apt-get -qy update
    - apt-get install -y make build-essential python3 python3-dev python3-setuptools python3-sphinx python3-pip

pages:
    script:
  # - apk --no-cache add python3-dev py-pip python3-sphinx
  # - apk --no-cache add make
        # - pip install sphinx
        - pip install numpy, sklearn
        - cd task_2/doc
        - make html
        - mv _build/html ../../public
        - cd ../..
    artifacts:
        paths:
            - public
    only:
        - master
