image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - doc
  - pages

before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE/test_doc:task_4

# build:
#     stage: build
#     script:
#         - docker build -t $CONTAINER_IMAGE .
#         - docker push $CI_REGISTRY_IMAGE/test_doc:task_4

# test:
#     stage: test
#     script:
#         - docker pull $CONTAINER_IMAGE
#         # - doceker run cd doc
#         - docker run $CONTAINER_IMAGE

# doc:
#     stage: doc
#     script:
#         - docker pull $CONTAINER_IMAGE
#         - docker run -w /project/doc $CONTAINER_IMAGE sphinx-apidoc -f -o . ..

pages:
    stage: pages
    script:
        - docker pull $CONTAINER_IMAGE
        - docker run -w /project/doc $CONTAINER_IMAGE make html
        - docker run $CONTAINER_IMAGE mv /project/doc/_build/html /project/public
    artifacts:
        paths:
            - /project/public
    # only:
    #     - master
    #     - release
