#image: ubuntu
#
#before_script:
#    - apt-get -qy update
#    - apt-get install -y make build-essential python3 python3-dev python3-setuptools python3-sphinx python3-pips
#    # - apk --no-cache add python3 python3-dev py-pip
#    # - apk --no-cache add make

image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - doc
  - pages

before_script:
  - docker info

variables:
  CONTAINER_IMAGE: registry.gitlab.com/se_ml_course/ostroukhovpa/test_doc:task_4

build:
    stage: build
    script:
        # - echo $CI_LOGIN_TOKEN
        - echo $CI_JOB_TOKEN
        # - docker build -t $CONTAINER_IMAGE .
        # - docker login registry.gitlab.com -u gitlab-ci-token -p $CI_LOGIN_TOKEN
        # - docker push $CONTAINER_IMAGE

# test:
#     stage: test
#     image: "registry.gitlab.com/se_ml_course/ostroukhovpa/test_doc:task_4"
#     script:
#         - python3 test_project.py

# doc:
#     stage: doc
#     image: "registry.gitlab.com/se_ml_course/ostroukhovpa/test_doc:task_4"
#     script:
#         - cd doc
# #    - sphinx-quickstart \
# #      --sep "n"           \
# #      --dot _           \
# #      -p ostroukhovpa   \
# #      -a "Ostroukhov PA"\
# #      -v 1.0            \
# #      -r 1.0            \
# #      -l en             \
# #      --suffix .rst     \
# #      --master index    \
# #      --epub "n"          \
# #      --makefile        \
# #      --no-batchfile    \
# #      --ext-autodoc
#         - sphinx-apidoc -o . ..

# pages:
#     image: "registry.gitlab.com/se_ml_course/ostroukhovpa/test_doc:task_4"
#     script:
#         - make html
#         - mv _build/html ../public
#     artifacts:
#         paths:
#             - /project/public
#     only:
#         - master
#         - release
