#image: ubuntu
#
#before_script:
#    - apt-get -qy update
#    - apt-get install -y make build-essential python3 python3-dev python3-setuptools python3-sphinx python3-pips
#    # - apk --no-cache add python3 python3-dev py-pip
#    # - apk --no-cache add make

image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - doc

before_script:
  - docker info

variables:
  CONTAINER_IMAGE: registry.gitlab.com/se_ml_course/ostroukhovpa/task_4:latest

build:
    stage: build
    script:
        - docker build -t $CONTAINER_IMAGE .

test:
    stage: test
    image: "registry.gitlab.com/se_ml_course/ostroukhovpa/task_4:latest"
    script:
        - python3 test_project.py

doc:
    stage: doc
    image: "registry.gitlab.com/se_ml_course/ostroukhovpa/task_4:latest"
    script:
        - cd doc
#    - sphinx-quickstart \
#      --sep "n"           \
#      --dot _           \
#      -p ostroukhovpa   \
#      -a "Ostroukhov PA"\
#      -v 1.0            \
#      -r 1.0            \
#      -l en             \
#      --suffix .rst     \
#      --master index    \
#      --epub "n"          \
#      --makefile        \
#      --no-batchfile    \
#      --ext-autodoc
        - sphinx-apidoc -o . ..

pages:
    image: "registry.gitlab.com/se_ml_course/ostroukhovpa/task_4:latest"
    script:
        - make html
        - mv _build/html ../public
    artifacts:
        paths:
            - /project/public
    only:
        - master
        - release

#image: ubuntu
#
#stages:
#  - test
##  - doc
##  - deploy
#
#variables:
#  CONTAINER_TEST_IMAGE: registry.gitlab.com/se_ml_course/ostroukhovpa/test:task_4
#
#before_script:
#    - apt-get -qy update
#    - apt-get install -y make build-essential python3 python3-dev python3-setuptools python3-sphinx python3-pips
#
#test:
#    script:
#        - docker run $CONTAINER_TEST_IMAGE
#
#pages:
#    script:
#        - pip3 install sphinx numpy scipy pandas sklearn
#        - cd doc
#        - make html
#        - mv _build/html ../public
#        - cd ..
#    artifacts:
#        paths:
#            - public
#    only:
#        - master
