FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y python3-pip python3-dev build-essential
COPY requirements.txt model.py test_project.py /app/
WORKDIR /app/
RUN pip3 install --upgrade pip
RUN pip3 install --default-timeout=100 -r requirements.txt
CMD ["python3", "test_project.py"]